sudo: false
language: java
jdk:
- oraclejdk8
script: "./gradlew clean build jar javadoc install"
after_script: "bash ./scripts/after-script.sh"
deploy:
  provider: releases
  api_key: "$GH_TOKEN"
  file: "buils/libs/*"
  skip_cleanup: true
  on:
    tags: true
    condition: '"$(ls ${HOME}/.m2/repository/${MAVEN_GROUP}/${PROJECT} | sed \"s/maven-metadata-local.xml//\" | xargs | grep -o SNAPHOT)" != "SNAPSHOT"'
