language: java
jdk:
- oraclejdk8
script: "./gradlew clean build jar javadoc install"
before_deploy:
  - export FILE=$(ls build/libs/*.jar)
deploy:
  - provider: releases
    api_key: "$GH_TOKEN"
    file: "${FILE}"
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: bash scripts/deploy.sh
    skip_cleanup: true
    on:
      tags: true
notifications:
  email:
    on_success: never
    on_failure: always
