name: BukkitSurvivalGames
main: io.github.m0pt0pmatt.spongesurvivalgames.BukkitSurvivalGamesPlugin
version: 1.0
permissions:
    spongesurvivalgameadmin:
      default: true
commands:
  spongesurvivalgames:
    aliases: ssg
    usage: /ssg [args]
    description: Base command for Sponge/Bukkit Survival Games
    permission: spongesurvivalgameadmin